# Generated by Django 5.2.8 on 2025-11-12 18:51

import django.contrib.gis.db.models.fields
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('AWAITING_PREPARATION', 'Awaiting Preparation'), ('PENDING_ACCEPTANCE', 'Pending Acceptance'), ('ACCEPTED', 'Accepted'), ('AT_STORE', 'At Store'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='AWAITING_PREPARATION', max_length=30)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('at_store_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, help_text='Customer ko dikhane wala ETA', null=True)),
                ('rider_rating', models.PositiveIntegerField(blank=True, help_text='Customer ne rider ko kya rating di (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rider_rating_comment', models.TextField(blank=True, help_text='Customer ka comment', null=True)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('vehicle_details', models.CharField(blank=True, help_text='Gaadi ka number (e.g., KA 01 AB 1234)', max_length=100)),
                ('admin_notes', models.TextField(blank=True, help_text="Admin ke notes (e.g., 'Rejected due to invalid license')", null=True)),
            ],
            options={
                'verbose_name': 'Rider Application',
                'verbose_name_plural': 'Rider Applications',
            },
        ),
        migrations.CreateModel(
            name='RiderCashDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Rider ne kitna amount deposit kiya', max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='UPI', max_length=20)),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='UPI/Bank Transaction ID (Rider provide karega)', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Rider ke notes (optional)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text="Admin ke notes (e.g., 'Checked in bank')", null=True)),
            ],
            options={
                'verbose_name': 'Rider Cash Deposit',
                'verbose_name_plural': 'Rider Cash Deposits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('DRIVING_LICENSE', 'Driving License'), ('AADHAAR_CARD', 'Aadhaar Card'), ('VEHICLE_RC', 'Vehicle RC Book'), ('OTHER', 'Other')], max_length=30)),
                ('document_file', models.FileField(help_text='Document ki scan copy (Image/PDF)', upload_to='rider_documents/')),
                ('is_verified', models.BooleanField(default=False, help_text='Kya admin ne is document ko verify kar liya hai?')),
            ],
            options={
                'verbose_name': 'Rider Document',
                'verbose_name_plural': 'Rider Documents',
            },
        ),
        migrations.CreateModel(
            name='RiderEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id_str', models.CharField(db_index=True, help_text='Order ID ka snapshot (search ke liye)', max_length=15)),
                ('base_fee', models.DecimalField(decimal_places=2, help_text='Is delivery ke liye fix kamai', max_digits=10)),
                ('tip', models.DecimalField(decimal_places=2, default=0.0, help_text='Customer se mili tip', max_digits=10)),
                ('total_earning', models.DecimalField(decimal_places=2, help_text='Kul kamai (Base Fee + Tip)', max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], db_index=True, default='UNPAID', help_text='Kya is kamai ka payment ho chuka hai?', max_length=10)),
            ],
            options={
                'verbose_name': 'Rider Earning',
                'verbose_name_plural': 'Rider Earnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Rider ko kitna amount pay kiya gaya', max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Payment kab process hua')),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH_ADJUSTMENT', 'Cash Adjustment'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin ke liye notes (e.g., Transaction ID)', null=True)),
            ],
            options={
                'verbose_name': 'Rider Payout',
                'verbose_name_plural': 'Rider Payouts',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Rider ki current live location (Longitude, Latitude)', null=True, srid=4326)),
                ('is_online', models.BooleanField(db_index=True, default=False, help_text='Kya rider duty par hai aur orders ke liye available hai?')),
                ('on_delivery', models.BooleanField(db_index=True, default=False, help_text='Kya rider abhi koi order deliver kar raha hai?')),
                ('vehicle_details', models.CharField(blank=True, help_text='e.g., Bike - KA 01 AB 1234', max_length=100)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=3, null=True)),
                ('cash_on_hand', models.DecimalField(decimal_places=2, default=0.0, help_text='Rider ke paas kitna COD cash hai jo usse company ko dena hai', max_digits=10)),
            ],
            options={
                'verbose_name': 'Rider Profile',
                'verbose_name_plural': 'Rider Profiles',
            },
        ),
    ]
