# Generated by Django 5.2.8 on 2025-11-12 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order'),
        ),
        migrations.AddField(
            model_name='riderapplication',
            name='user',
            field=models.OneToOneField(help_text='Kaun sa user apply kar raha hai', on_delete=django.db.models.deletion.CASCADE, related_name='rider_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ridercashdeposit',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Kis admin/staff ne approve kiya', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='application',
            field=models.ForeignKey(help_text='Yeh document kis application ka hissa hai', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='delivery.riderapplication'),
        ),
        migrations.AddField(
            model_name='riderearning',
            name='delivery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earning_record', to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='riderpayout',
            name='earnings_covered',
            field=models.ManyToManyField(help_text='Is payout mein kaun si earnings shaamil hain', related_name='payout_records', to='delivery.riderearning'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='delivery.riderapplication'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riderpayout',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='delivery.riderprofile'),
        ),
        migrations.AddField(
            model_name='riderearning',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='delivery.riderprofile'),
        ),
        migrations.AddField(
            model_name='ridercashdeposit',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_deposits', to='delivery.riderprofile'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.riderprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='riderdocument',
            unique_together={('application', 'document_type')},
        ),
    ]
