# Generated by Django 5.2.8 on 2025-11-12 18:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Banner ka title (Admin mein pehchanne ke liye)', max_length=200)),
                ('image', models.ImageField(help_text='Banner ki image (e.g., 1080x500 pixels)', upload_to='banners/')),
                ('link', models.URLField(blank=True, help_text='Banner par click karne par kahan jaana hai (Optional link)', max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Banners ko sort karne ke liye (0 sabse pehle dikhega)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Kya yeh banner abhi active hai?')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Dark store ka naam (e.g., 'Koramangala Hub')", max_length=100)),
                ('address', models.TextField(help_text='Store ka poora address')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Store ki exact location (Longitude, Latitude)', null=True, srid=4326)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Kya yeh store operations ke liye active hai?')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text="Category ka naam (e.g., 'Dairy & Breakfast')", max_length=150)),
                ('slug', models.SlugField(help_text="URL ke liye unique slug (e.g., 'dairy-breakfast')", max_length=150, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Category ke liye ek chhota icon', null=True, upload_to='category_icons/')),
                ('is_active', models.BooleanField(default=True, help_text='Kya yeh category site par visible hai?')),
                ('parent', models.ForeignKey(blank=True, help_text='Is category ka parent (agar yeh ek sub-category hai)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text="Product ka naam (e.g., 'Amul Taaza Milk')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Product ke baare mein detail jaankari')),
                ('brand', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('main_image', models.ImageField(help_text='Product ki primary image', upload_to='product_images/')),
                ('is_active', models.BooleanField(default=True, help_text='Kya yeh product line active hai?')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Sabhi reviews ki average rating', max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0, help_text='Kitne logo ne review diya hai')),
                ('category', models.ForeignKey(help_text='Yeh product kis category mein aata hai', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_name', models.CharField(help_text="Variant ka naam (e.g., '500ml Pouch', '1kg Packet', 'Red')", max_length=255)),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit - har variant ke liye unique', max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Agar is variant ki image alag hai toh yahaan daalein', null=True, upload_to='variant_images/')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='JSON format mein attributes (e.g., size, color, weight)')),
                ('product', models.ForeignKey(help_text='Yeh variant kis base product ka hai', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating (1 se 5 star)')),
                ('comment', models.TextField(blank=True, help_text='Customer ka text review')),
                ('product', models.ForeignKey(help_text='Kis product ke liye review hai', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
                ('user', models.ForeignKey(help_text='Kis user ne review diya', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
