# Generated by Django 5.2.8 on 2025-11-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome class (e.g., 'fas fa-carrot')", max_length=100, null=True),
        ),
    ]
