# Generated by Django 5.2.8 on 2025-11-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storestaffprofile',
            name='can_pick_orders',
        ),
        migrations.RemoveField(
            model_name='storestaffprofile',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='storestaffprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('MANAGER', 'Store Manager'), ('ShiftIncherg', 'Shift Incherg'), ('PICKER', 'Order Picker')], help_text='Employee ka designation', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('STAFF', 'Staff'), ('RIDER', 'Rider')], db_index=True, default='CUSTOMER', max_length=20),
        ),
    ]
