# Generated by Django 5.2.8 on 2025-11-12 18:51

import django.db.models.deletion
import support.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.CharField(db_index=True, default=support.models.generate_ticket_id, editable=False, max_length=15, unique=True)),
                ('subject', models.CharField(help_text='Aapki problem ka short title', max_length=255)),
                ('category', models.CharField(choices=[('ORDER_ISSUE', 'Order Issue'), ('PAYMENT_ISSUE', 'Payment Issue'), ('DELIVERY_ISSUE', 'Delivery Issue'), ('TECHNICAL_ISSUE', 'Technical Issue'), ('ACCOUNT_ISSUE', 'Account Issue'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending (Awaiting Customer Reply)'), ('IN_PROGRESS', 'In Progress (Staff Working)'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('is_internal_note', models.BooleanField(default=False, help_text='Internal note (customer ko nahi dikhega)')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
