# Generated by Django 5.2.8 on 2025-11-12 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Location ka unique code (e.g., 'A-01-R1-S1' ya 'RACK-A')", max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='store.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PickTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_to_pick', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ISSUE', 'Issue Reported')], db_index=True, default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('picker_notes', models.TextField(blank=True, help_text='Picker dwara report ki gayi issue (agar koi hai)', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Kaun sa picker yeh kaam karega (StoreStaff user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_tasks', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Kis location se uthana hai', on_delete=django.db.models.deletion.PROTECT, to='wms.location')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_tasks', to='orders.order')),
                ('variant', models.ForeignKey(help_text='Kaun sa item uthana hai', on_delete=django.db.models.deletion.PROTECT, to='store.productvariant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WmsStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('inventory_summary', models.ForeignKey(help_text='Yeh WMS entry kis StoreInventory item se judi hai', on_delete=django.db.models.deletion.CASCADE, related_name='wms_entries', to='inventory.storeinventory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='wms.location')),
            ],
            options={
                'ordering': ['location__code'],
                'unique_together': {('inventory_summary', 'location')},
            },
        ),
    ]
