# Generated by Django 5.2.8 on 2025-11-12 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Customer ke liye Selling Price (MRP)', max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted price', max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Is variant ka kitna stock available hai')),
                ('is_available', models.BooleanField(default=True, help_text='Kya yeh item abhi bikri ke liye available hai?')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text="Kya yeh product Home Page par 'Featured' section mein dikhega?")),
                ('store', models.ForeignKey(help_text='Kis dark store ka inventory item hai', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='store.store')),
                ('variant', models.ForeignKey(help_text="Kaun sa product variant (e.g., '500ml milk pouch')", on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='store.productvariant')),
            ],
            options={
                'verbose_name_plural': 'Store Inventories',
                'unique_together': {('store', 'variant')},
            },
        ),
    ]
