# Generated by Django 5.2.8 on 2025-11-12 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='inventory_item',
            field=models.ForeignKey(help_text='Stock se ek specific item variant', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='inventory.storeinventory'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'inventory_item')},
        ),
    ]
