"""
Django settings for quickdash project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging # <-- ADD
from pathlib import Path
import platform
import os
from decouple import config
from dotenv import load_dotenv
# from dotenv import load_dotenv # <-- REMOVED (Duplicate)
# from pathlib import Path # <-- REMOVED (Duplicate)
# import platform # <-- REMOVED (Duplicate)
# import os # <-- REMOVED (Duplicate)
# from decouple import config # <-- REMOVED (Duplicate)



load_dotenv()



BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# --- Firebase Admin SDK ---
# Initialization logic has been moved to accounts/apps.py in the ready() method.
# Hum yahaan sirf key file ka path define kar rahe hain.
SERVICE_ACCOUNT_KEY_FILE = BASE_DIR / 'serviceAccountKey.json'
# --- End Firebase Admin SDK ---

DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"


ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd Party Apps
    'rest_framework',
    'django.contrib.gis',
    'rest_framework_simplejwt',
    'corsheaders',            
    

    # My Apps
    'accounts.apps.AccountsConfig', # <-- UPDATED (To load ready() method)
    'store',
    'inventory',
    'cart',
    'orders',
    'delivery',
    'wms',
    'support',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'quickdash.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'quickdash.wsgi.application'
ASGI_APPLICATION = 'quickdash.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),      
        'PASSWORD': config('DB_PASSWORD'), 
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# My custom codes 
AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}



# --- GeoDjango Configuration for Linux ---

if platform.system() == "Linux":
    os.environ['GDAL_LIBRARY_PATH'] = '/usr/lib/libgdal.so'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1", 
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0' 
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata' 

# CHANNELS (WebSockets)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)], 
        },
    },
}

# --- Staff Google Login Settings ---
# Yeh aapka company domain hai
COMPANY_GOOGLE_DOMAIN = "Qickdash.com" 

# Yeh aapko Google Cloud Console se milega
# (Frontend (Web/Android) wala Client ID yahaan daalein)
GOOGLE_STAFF_CLIENT_ID = config('GOOGLE_STAFF_CLIENT_ID', default=None)

# Razorpay Settings
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET')
RAZORPAY_WEBHOOK_SECRET = config('RAZORPAY_WEBHOOK_SECRET', default=None) # Humne isse pehle add kiya tha

# --- NAYA SMS Gateway Settings (Twilio Example) ---
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default=None)
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default=None)
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default=None)
# --- END Naya Code ---



# Delivery & Order Settings
BASE_DELIVERY_FEE = 20.00  # (Aapki default fee)
FEE_PER_KM = 5.00         # (Aapki per-km fee)
MIN_DELIVERY_FEE = 20.00  # (Minimum fee)
MAX_DELIVERY_FEE = 100.00 # (Maximum fee)
TAX_RATE = 0.05           # (e.g., 5% GST)
ORDER_CANCELLATION_WINDOW = 300
RIDER_BASE_DELIVERY_FEE = 30.00
RIDER_SEARCH_RADIUS_KM = 1

# --- Production Storage (S3) vs Local Storage ---

# Production mein .env file mein USE_S3=True set karein
USE_S3 = config('USE_S3', default=False, cast=bool) 

# Setup logger (zaroori hai kyunki settings pehle load hoti hain)
logger = logging.getLogger(__name__)

if USE_S3:
    # --- PRODUCTION STORAGE (S3) ---
    logger.info("STATUS: Using S3 for file storage (Production Mode)")
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='ap-south-1') # Default region
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    
    # Media Files (User Uploads - Zaroori)
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    
    # Agar static files bhi S3 par hain toh yeh line uncomment karein
    # STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'
    # STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'


else:
    # --- LOCAL DEVELOPMENT STORAGE ---
    logger.info("STATUS: Using local file storage (Development Mode)")
    STATIC_URL = 'static/'
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'