"""
Django settings for quickdash project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging # <-- ADD
from pathlib import Path
import platform
import os
from decouple import config
# from dotenv import load_dotenvimport os
from dotenv import load_dotenv
import os
from decimal import Decimal # <-- YEH NAYA IMPORT HAI




load_dotenv()



BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# --- Firebase Admin SDK ---
# Initialization logic has been moved to accounts/apps.py in the ready() method.
# Hum yahaan sirf key file ka path define kar rahe hain.
SERVICE_ACCOUNT_KEY_FILE = BASE_DIR / 'serviceAccountKey.json'
# --- End Firebase Admin SDK ---

DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"


# --- FIX 1: ALLOWED_HOSTS ko .env se load karein ---
# .env file mein: DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,your-domain.com
ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', default='127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd Party Apps
    'rest_framework',
    'django.contrib.gis',
    'rest_framework_simplejwt',
    'corsheaders',            
    

    # My Apps
    'accounts.apps.AccountsConfig', # <-- UPDATED (To load ready() method)
    'store',
    'inventory',
    'cart',
    'orders',
    'delivery',
    'wms',
    'support',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # --- FIX 2: CORS ko CommonMiddleware se pehle rakhein ---
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 'corsheaders.middleware.CorsMiddleware', # <-- Yahaan se move kar diya
]

ROOT_URLCONF = 'quickdash.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'web/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'quickdash.wsgi.application'
ASGI_APPLICATION = 'quickdash.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),      
        'PASSWORD': config('DB_PASSWORD'), 
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# --- TIME_ZONE ko config se lein (Best Practice) ---
TIME_ZONE = config('TIME_ZONE', default='UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR/ 'web/static',
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# My custom codes 
AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}



# --- GeoDjango Configuration for Linux ---

if platform.system() == "Linux":
    # NAYA SAHI PATH YAHAN DAALEIN
    os.environ['GDAL_LIBRARY_PATH'] = '/usr/lib/x86_64-linux-gnu/libgdal.so'
# NAYA SAHI PATH YAHAN DAALEIN
GDAL_LIBRARY_PATH = os.getenv('GDAL_LIBRARY_PATH', '/usr/lib/x86_64-linux-gnu/libgdal.so')


# --- FIX 3: CORS ko .env se load karein ---
# .env file mein: DJANGO_CORS_ALLOWED_ORIGINS=http://localhost:3000,https://your-frontend.com
CORS_ALLOWED_ORIGINS = config('DJANGO_CORS_ALLOWED_ORIGINS', default='').split(',')
# Agar aapka .env variable set nahi hai, toh development ke liye default set karein
if not config('DJANGO_CORS_ALLOWED_ORIGINS', default=None):
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]


# --- FIX 4: Redis (Cache, Celery, Channels) ko .env se load karein ---
# .env file mein: REDIS_URL=redis://your-production-redis-url:port
# Hum 3 alag-alag database numbers ka istemaal karenge (0, 1, 2)
DEFAULT_REDIS_URL = 'redis://127.0.0.1:6379'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # Production mein 'REDIS_URL_CACHE' set karein (e.g., redis://.../1)
        "LOCATION": config('REDIS_URL_CACHE', default=f'{DEFAULT_REDIS_URL}/1'), 
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# Production mein 'CELERY_BROKER_URL' set karein (e.g., redis://.../0)
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=f'{DEFAULT_REDIS_URL}/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=f'{DEFAULT_REDIS_URL}/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata' 

# CHANNELS (WebSockets)
# Production mein 'CHANNELS_REDIS_URL' set karein (e.g., redis://.../2)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [config('CHANNELS_REDIS_URL', default=f'{DEFAULT_REDIS_URL}/2')], 
        },
    },
}
# --- END FIX 4 ---


# --- Staff Google Login Settings ---
# Yeh aapka company domain hai
# --- FIX 5: Google Domain ko .env se load karein ---
COMPANY_GOOGLE_DOMAIN = config("COMPANY_GOOGLE_DOMAIN", default="Qickdash.com") 

# Yeh aapko Google Cloud Console se milega
# (Frontend (Web/Android) wala Client ID yahaan daalein)
GOOGLE_STAFF_CLIENT_ID = config('GOOGLE_STAFF_CLIENT_ID', default=None)

# Razorpay Settings
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET')
RAZORPAY_WEBHOOK_SECRET = config('RAZORPAY_WEBHOOK_SECRET', default=None) # Humne isse pehle add kiya tha

# --- NAYA SMS Gateway Settings (Twilio Example) ---
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default=None)
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default=None)
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default=None)
# --- END Naya Code ---




# --- FIX 6: Business Logic ko .env se load karein ---
# (Decimal import zaroori hai)
BASE_DELIVERY_FEE = config('BASE_DELIVERY_FEE', default='20.00', cast=Decimal)
FEE_PER_KM = config('FEE_PER_KM', default='5.00', cast=Decimal)
MIN_DELIVERY_FEE = config('MIN_DELIVERY_FEE', default='20.00', cast=Decimal)
MAX_DELIVERY_FEE = config('MAX_DELIVERY_FEE', default='100.00', cast=Decimal)
TAX_RATE = config('TAX_RATE', default='0.05', cast=Decimal) # 5%
ORDER_CANCELLATION_WINDOW = config('ORDER_CANCELLATION_WINDOW', default=300, cast=int) # 5 minutes
RIDER_BASE_DELIVERY_FEE = config('RIDER_BASE_DELIVERY_FEE', default='30.00', cast=Decimal)
RIDER_SEARCH_RADIUS_KM = config('RIDER_SEARCH_RADIUS_KM', default=1.0, cast=float)
LOW_STOCK_THRESHOLD = config('LOW_STOCK_THRESHOLD', default=10, cast=int) # Dashboard ke liye
# --- END FIX 6 ---


# --- Production Storage (S3) vs Local Storage ---

# Production mein .env file mein USE_S3=True set karein
USE_S3 = config('USE_S3', default=False, cast=bool) 

# Setup logger (zaroori hai kyunki settings pehle load hoti hain)
logger = logging.getLogger(__name__)


"""
# --- FIX 7: S3 Logic ko UNCOMMENT karein ---
if USE_S3:
    # --- PRODUCTION STORAGE (S3) ---
    logger.info("STATUS: Using S3 for file storage (Production Mode)")
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='ap-south-1') # Default region
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    
    # Media Files (User Uploads - Zaroori)
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    
    # Agar static files bhi S3 par hain toh yeh line uncomment karein
    # STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'
    # STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'


else:
    # --- LOCAL DEVELOPMENT STORAGE ---
    logger.info("STATUS: Using local file storage (Development Mode)")
    STATIC_URL = 'static/'
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
# --- END FIX 7 ---

"""