# Generated by Django 5.2.8 on 2025-11-12 18:51

import django.db.models.deletion
import django.utils.timezone
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('inventory', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text="Coupon code (e.g., 'SAVE10', 'FREEDELIVERY')", max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount')], default='FIXED_AMOUNT', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (e.g., 10.00 for 10% or 100.00 for ₹100)', max_digits=10)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Coupon istemaal karne ke liye minimum cart total', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage coupons ke liye maximum discount limit', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(help_text='Coupon ki expiry date/time')),
                ('is_active', models.BooleanField(default=True, help_text='Kya yeh coupon abhi active hai?')),
                ('max_uses', models.PositiveIntegerField(default=100, help_text='Yeh coupon kitni baar istemaal ho sakta hai (total)')),
                ('times_used', models.PositiveIntegerField(default=0, editable=False, help_text='Yeh coupon kitni baar istemaal ho chuka hai')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(db_index=True, default=orders.models.generate_order_id, editable=False, max_length=15, unique=True, verbose_name='Order ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('item_subtotal', models.DecimalField(decimal_places=2, help_text='Sirf items ka total price', max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('taxes_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxes')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount Amount')),
                ('rider_tip', models.DecimalField(decimal_places=2, default=0.0, help_text='Customer dwara di gayi tip', max_digits=10, verbose_name='Rider Tip')),
                ('final_total', models.DecimalField(decimal_places=2, help_text='Subtotal + Delivery Fee + Taxes - Discount', max_digits=10, verbose_name='Grand Total')),
                ('special_instructions', models.TextField(blank=True, help_text="Customer ke special instructions (e.g., 'less spicy')", null=True)),
                ('coupon', models.ForeignKey(blank=True, help_text='Is order par apply kiya gaya coupon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon')),
                ('delivery_address', models.ForeignKey(help_text='Order ke waqt select kiya gaya address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.store')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product ka naam (snapshot)', max_length=255)),
                ('variant_name', models.CharField(help_text='Variant ka naam (snapshot)', max_length=255)),
                ('price_at_order', models.DecimalField(decimal_places=2, help_text='Item ka price (snapshot)', max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storeinventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, help_text='Razorpay se mili Order ID', max_length=255, null=True)),
                ('transaction_id', models.CharField(db_index=True, help_text='Payment gateway se mili ID (e.g., razorpay_payment_id)', max_length=255, unique=True)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('STRIPE', 'Stripe'), ('RAZORPAY', 'Razorpay'), ('OTHER', 'Other')], default='COD', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Kitna amount pay hua', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_gateway_response', models.JSONField(blank=True, default=dict, help_text='Gateway se mila poora response (JSON)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
